---
version: '3.1'
services:
  db:
    image: docker.io/postgres
    command: '-c max_connections=5000'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh:z
    ports:
      - "5432:5432"
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: docker.io/confluentinc/cp-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
  kafka-rest:
    image: docker.io/confluentinc/cp-kafka-rest
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
  kafka-topics-ui:
    image: docker.io/landoop/kafka-topics-ui
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true
    ports:
      - "3030:8000"
    depends_on:
      - kafka-rest
  inventory:
    image: quay.io/cloudservices/insights-inventory
    environment:
      - INVENTORY_LOG_LEVEL=DEBUG
      - INVENTORY_DB_HOST=db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
      - db
  //TODO need to connect this pod to the db pod
  swatch-producer-aws:
    image: quay.io/lburnett/rhsm:02162022
    environment:
      - QUARKUS_PROFILE=dev
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - db