# This file defines properties that are common to all swatch services.
# import via:
# spring:
#   config:
#     import: classpath:swatch-core/application.yaml

management:
  endpoints:
    web:
      exposure:
        include:
          - hawtio
          - health
          - info
          - jolokia
          - prometheus
  endpoint:
    shutdown:
      enabled: true
    prometheus:
      enabled: true

spring:
  jmx:
    enabled: ${JMX_ENABLED:true}
  # general hibernate configurations
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: ${JDBC_BATCH_SIZE:100}
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:/liquibase/changelog.xml

# See https://hawt.io/docs/configuration/ for details on built-in hawtio config
hawtio:
  # disable the remote connection tab, we do not need it
  disableProxy: ${HAWTIO_DISABLE_PROXY:true}
  authenticationEnabled: ${HAWTIO_AUTHENTICATION_ENABLED:false}
  proxyAllowlist: ${HAWTIO_PROXY_ALLOWLIST:localhost,127.0.0.1}
  localAddressProbing: ${HAWTIO_LOCAL_ADDRESS_PROBING:true}

rhsm-subscriptions:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_DATABASE:rhsm-subscriptions}?reWriteBatchedInserts=true&stringtype=unspecified&sslmode=${DATABASE_SSL_MODE:disable}&sslrootcert=${DATABASE_SSL_CERT:/dev/null}
    username: ${DATABASE_USERNAME:rhsm-subscriptions}
    password: ${DATABASE_PASSWORD:rhsm-subscriptions}
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    hikari:
      connection-timeout: ${DATABASE_CONNECTION_TIMEOUT_MS:30000}
      maximum-pool-size: ${DATABASE_MAX_POOL_SIZE:10}
  # Base path override for reverse proxy support
  hawtio-base-path: ${HAWTIO_BASE_PATH:}
