rhsm-subscriptions:
  tally-retention-policy:
    # 70 days worth
    hourly: ${TALLY_RETENTION_HOURLY:1680}

    # A year and change
    daily: ${TALLY_RETENTION_DAILY:370}

    # Roughly 3 months worth
    weekly: ${TALLY_RETENTION_WEEKLY:12}

    # A year's worth
    monthly: ${TALLY_RETENTION_MONTHLY:12}

    # Four year's worth
    quarterly: ${TALLY_RETENTION_QUARTERLY:16}

    yearly: ${TALLY_RETENTION_YEARLY:5}
