rhsm-subscriptions:
  pretty-print-json: ${PRETTY_PRINT_JSON:false}
  rbac-service:
    application-name: ${RBAC_APPLICATION_NAME:subscriptions}
    use-stub: ${RBAC_USE_STUB:false}
    url: http://${RBAC_HOST:localhost}:${RBAC_PORT:8819}/api/rbac/v1
    max-connections: ${RBAC_MAX_CONNECTIONS:100}
    stub-permissions: ${RBAC_STUB_PERMISSIONS:subscriptions:*:*}
