resteasy:
  jaxrs:
    app:
      registration: property
      classes: org.candlepin.insights.JaxrsApplication
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
