rhsm-subscriptions:
  # Use Spring Resource notation for this (e.g. "classpath:" or "file:")
  role-to-products-map-resource-location: classpath:role_to_products_map.yaml
  arch-to-product-map-resource-location: classpath:arch_to_product_map.yaml
  account-list-resource-location: ${ACCOUNT_LIST_RESOURCE_LOCATION:}
  account-batch-size: ${ACCOUNT_BATCH_SIZE:1}

  metering:
    tasks:
      topic: ${METERING_KAFKA_TOPIC:platform.rhsm-subscriptions.metering-tasks}
      kafka-group-id: ${METERING_KAFKA_GROUP_ID:rhsm-subscriptions-metering-task-processor}

    prometheus:
      client:
        token: ${PROM_AUTH_TOKEN:}
        url: ${PROM_URL:https://localhost/api/v1}
