rhsm-subscriptions:
  # Use Spring Resource notation for this (e.g. "classpath:" or "file:")
  account-list-resource-location: ${ACCOUNT_LIST_RESOURCE_LOCATION:}
  account-batch-size: ${ACCOUNT_BATCH_SIZE:1}

  metering:
    prometheus:
      metric:
        openshift:
          metricPromQL: group(subscription_labels{ebs_account='%s',support=~'Premium|Standard|Self-Support|None'})by(_id,ebs_account)*on(_id) group_right(ebs_account) cluster:usage:workload:capacity_physical_cpu_cores:min:5m
          subscriptionLabelPromQL: group(cluster:usage:workload:capacity_physical_cpu_cores:min:5m) by (_id)*on(_id) group_right (ebs_acount) subscription_labels{ebs_account='%s',support=~'Premium|Standard|Self-Support|None'}
      client:
        token: ${PROM_AUTH_TOKEN:}
        url: ${PROM_URL:https://localhost/api/v1}
