# See https://goessner.net/articles/JsonPath/ for JSON Path syntax
RBAC_HOST: ${clowder.endpoints[?(@.app == 'rbac')].hostname:localhost}
RBAC_PORT: ${clowder.endpoints[?(@.app == 'rbac')].port:8819}

rhsm-subscriptions:
  pretty-print-json: ${PRETTY_PRINT_JSON:false}
  rbac-service:
    application-name: ${RBAC_APPLICATION_NAME:subscriptions}
    use-stub: ${RBAC_USE_STUB:false}
    url: http://${RBAC_HOST}:${RBAC_PORT}/api/rbac/v1
    max-connections: ${RBAC_MAX_CONNECTIONS:100}
    stub-permissions: ${RBAC_STUB_PERMISSIONS:subscriptions:*:*}
