name: RHELProducts
products:
  - product: 68 # Red Hat Enterprise Linux Desktop
    productIds:
      - RHEL
      - RHEL for x86
      - RHEL Desktop
  - product: 69 # Red Hat Enterprise Linux Server
    productIds:
      - RHEL
      - RHEL for x86
      - RHEL Server
  - product: 71 # Red Hat Enterprise Linux Workstation
    productIds:
      - RHEL
      - RHEL for x86
      - RHEL Workstation
  - product: 72 # Red Hat Enterprise Linux for IBM z Systems
    productIds:
      - RHEL
      - RHEL for IBM z
  - product: 74 # Red Hat Enterprise Linux for Power, big endian
    productIds:
      - RHEL
      - RHEL for IBM Power
  - product: 76 # Red Hat Enterprise Linux for Scientific Computing
    productIds:
      - RHEL
      - RHEL for x86
      - RHEL Compute Node
  - product: 279 # Red Hat Enterprise Linux for Power, little endian
    productIds:
      - RHEL
      - RHEL for IBM Power
  - product: 419 # Red Hat Enterprise Linux for ARM 64
    productIds:
      - RHEL
      - RHEL for ARM
  - product: 420 # Red Hat Enterprise Linux for Power 9
    productIds:
      - RHEL
      - RHEL for IBM Power
  - product: 479 # Red Hat Enterprise Linux for x86_64 (RHEL8)
    productIds:
      - RHEL
      - RHEL for x86
finestGranularity: DAILY
burstable: false
syspurposeRoles:
  - name: Red Hat Enterprise Linux Server
    productIds:
      - RHEL
      - RHEL Server
  - name: Red Hat Enterprise Linux Workstation
    productIds:
      - RHEL
      - RHEL Workstation
  - name: Red Hat Enterprise Linux Compute Node
    productIds:
      - RHEL
      - RHEL Compute Node
architectureProductIdMap:
  aarch64: RHEL for ARM
  arm64: RHEL for ARM
  i386: RHEL for x86
  ppc64: RHEL for IBM Power
  ppc64le: RHEL for IBM Power
  s390x: RHEL for IBM z
  x86_64: RHEL for x86
---
name: SatelliteProducts
products:
  - product: 250 # Red Hat Satellite
    productIds:
      - Satellite
      - Satellite Server
  - product: 269 # Red Hat Satellite Capsule
    productIds:
      - Satellite
      - Satellite Capsule
finestGranularity: DAILY
burstable: false
syspurposeRoles: []
architectureProductIdMap: {}
---
name: OpenShift-metrics
products:
  - product: 290 # Red Hat OpenShift Container Platform
    productIds:
      - OpenShift Container Platform
syspurposeRoles:
  - name: ocp
    productIds:
      - OpenShift-metrics
  - name: osd
    productIds:
      - OpenShift-dedicated-metrics
finestGranularity: HOURLY
burstable: false
architectureProductIdMap: {}
