# load the common core definitions
spring:
  config:
    import: classpath:swatch-core/application.yaml
  kafka:  # TODO(khowell) this should be in swatch-core
    bootstrap-servers: ${KAFKA_BOOTSTRAP_HOST:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
    listener:
      # The number of threads that will be processing messages (should match
      # the number of partitions on the queue)
      concurrency: ${KAFKA_MESSAGE_THREADS:1}
      idle-event-interval: ${KAFKA_IDLE_EVENT_INTERVAL:5s}
    consumer:
      properties:
        # Required kafka defaults
        max.poll.interval.ms: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:1800000}
        reconnect.backoff.ms: ${KAFKA_CONSUMER_RECONNECT_BACKOFF_MS:2000}
        reconnect.backoff.max.ms: ${KAFKA_CONSUMER_RECONNECT_BACKOFF_MAX_MS:10000}
        default.api.timeout.ms: ${KAFKA_API_RECONNECT_TIMEOUT_MS:480000}
      # if no offset commit exists yet, set to earliest
      auto-offset-reset: earliest
      max-poll-records: 1
  profiles:
    active: kafka-queue  # NOTE(khowell): this should be unnecessary w/
rhsm-subscriptions:
  security:
    dev-mode: ${DEV_MODE:false}  # TODO(khowell) this should be in swatch-core
rhsm-conduit:
  rhsm:
    use-stub: ${RHSM_USE_STUB:false}
    url: ${RHSM_URL:http://localhost:9090}
    keystore-file: ${RHSM_KEYSTORE:}
    keystore-password: ${RHSM_KEYSTORE_PASSWORD:changeit}
    request-batch-size: ${RHSM_BATCH_SIZE:1000}
    max-connections: ${RHSM_MAX_CONNECTIONS:100}
    truststore-file: ${RHSM_TRUSTSTORE:}
    truststore-password: ${RHSM_TRUSTSTORE_PASSWORD:changeit}
  inventory-service:
    use-stub: ${INVENTORY_USE_STUB:true}
    api-key: ${INVENTORY_API_KEY:changeit}
    host-last-sync-threshold: ${INVENTORY_HOST_LAST_SYNC_THRESHOLD:24h}
    add-uuid-hyphens: ${INVENTORY_ADD_UUID_HYPHENS:false}
    # FIXME: misnamed, it's actually in hours
    stale-host-offset-in-days: ${INVENTORY_STALE_HOST_OFFSET_HOURS:48}
    kafka-host-ingress-topic: ${INVENTORY_HOST_INGRESS_TOPIC:platform.inventory.host-ingress}
  tasks:
    topic: ${CONDUIT_KAFKA_TOPIC:platform.rhsm-conduit.tasks}
    kafka-group-id: ${CONDUIT_KAFKA_GROUP_ID:rhsm-conduit-task-processor}
    seek-override-end: ${KAFKA_SEEK_OVERRIDE_END:false}
    seek-override-timestamp: ${KAFKA_SEEK_OVERRIDE_TIMESTAMP:}
