# This is a file maintained by the rhsm-subscriptions project that describes
# a portion of the Red Hat IT User API.
openapi: 3.0.2
info:
  title: user-api
  description: Third-party specification for User API
  version: 1.0.0

paths:
  /v2/findAccount:
    description: Find an account
    post:
      summary: Find Account
      operationId: findAccount
      tags:
        - account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountSearch'
      responses:
        '200':
          description: The operation completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '204':
          description: No account found

components:
  schemas:
    Account:
      required:
        - ebsAccountNumber
        - id
      properties:
        ebsAccountNumber:
          type: string
        id:
          type: string
    AccountSearch:
      required:
        - by
      properties:
        by:
          $ref: '#/components/schemas/AccountCriteria'
    AccountCriteria:
      properties:
        ebsAccountNumber:
          type: string
        id:
          type: string
