apiVersion: v1
kind: Service
metadata:
  name: rhsm-subscriptions-worker-monitoring
  labels:
    prometheus: rhsm
spec:
  ports:
    - port: 8080
      name: "8080"
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: rhsm-subscriptions-worker
