apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhsm-subscriptions-worker
spec:
  selector:
    matchLabels:
      deployment: rhsm-subscriptions-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: rhsm-subscriptions-worker
        prometheus: rhsm
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - image: quay.io/cloudservices/rhsm-subscriptions:latest
          name: rhsm-subscriptions-worker
          env:
            # turn off built-in jolokia, so that the spring boot jolokia actuator will work
            - name: AB_JOLOKIA_OFF
              value: 'true'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: logs
              mountPath: /logs
            - name: pinhead
              mountPath: /pinhead
          workingDir: /
      volumes:
        - name: config
          configMap:
            name: rhsm-subscriptions-config
        - name: splunk
          secret:
            secretName: splunk
        - name: logs
          emptyDir: {}
        - name: pinhead
          secret:
            secretName: pinhead
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
