apiVersion: v1
kind: Template
metadata:
  name: rhsm-subscriptions-jobs

parameters:
  - name: LOGGING_LEVEL_ROOT
    value: WARN
  - name: LOGGING_LEVEL
    value: INFO
  - name: RBAC_HOST
    required: true
  - name: KAFKA_BOOTSTRAP_HOST
    required: true
  - name: KAFKA_SCHEMA_REGISTRY_HOST
    required: true
  - name: KAFKA_MESSAGE_THREADS
    value: '24'
  - name: KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS
    value: '3600000'
  - name: REPLICAS
    value: '1'
  - name: IMAGE_TAG
    value: latest
  - name: MEMORY_REQUEST
    value: 100Mi
  - name: MEMORY_LIMIT
    value: 2Gi
  - name: CPU_REQUEST
    value: 200m
  - name: CPU_LIMIT
    value: '1'


objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: rhsm-subscriptions
      name: rhsm-subscriptions-jobs
    spec:
      replicas: ${REPLICAS}
      selector:
        deploymentconfig: rhsm-subscriptions-jobs
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: rhsm-subscriptions
            deploymentconfig: rhsm-subscriptions-jobs
          annotations:
            prometheus.io/path: /actuator/prometheus
            prometheus.io/port: '8080'
            prometheus.io/scrape: 'true'
        spec:
          containers:
            - image: quay.io/cloudservices/rhsm-subscriptions:${IMAGE_TAG}
              name: rhsm-subscriptions
              env:
                - name: JAVA_OPTIONS
                  value: -Dlogging.config=/config/logback.xml -Dspring.config.additional-location=file:/config/subscriptions.properties -Dspring.profiles.active=scheduler,worker
                - name: JAVA_MAX_MEM_RATIO
                  value: '85'
                - name: GC_MAX_METASPACE_SIZE
                  value: '256'
                - name: LOGGING_LEVEL_ROOT
                  value: ${LOGGING_LEVEL_ROOT}
                - name: LOGGING_LEVEL_ORG_CANDLEPIN
                  value: ${LOGGING_LEVEL}
                - name: KAFKA_BOOTSTRAP_HOST
                  value: ${KAFKA_BOOTSTRAP_HOST}
                - name: KAFKA_SCHEMA_REGISTRY_HOST
                  value: ${KAFKA_SCHEMA_REGISTRY_HOST}
                - name: KAFKA_MESSAGE_THREADS
                  value: ${KAFKA_MESSAGE_THREADS}
                - name: KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS
                  value: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS}
                - name: RBAC_HOST
                  value: ${RBAC_HOST}
                - name: RBAC_PORT
                  value: ${RBAC_PORT}
                - name: RHSM_SUBSCRIPTIONS_DATABASE_HOSTNAME
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-host
                - name: RHSM_SUBSCRIPTIONS_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-name
                - name: RHSM_SUBSCRIPTIONS_DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-user
                - name: RHSM_SUBSCRIPTIONS_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-password
                - name: INVENTORY_DATABASE_HOSTNAME
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: hostname
                - name: INVENTORY_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: database-name
                - name: INVENTORY_DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: username
                - name: INVENTORY_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: password
                - name: KEYSTORE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: keystore-password
                - name: TRUSTSTORE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: truststore-password
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 3
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 3
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8778
                  name: jolokia
                  protocol: TCP
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: secrets
                  mountPath: /secrets
              workingDir: /
          volumes:
            - name: config
              configMap:
                name: rhsm-subscriptions-config
            - name: secrets
              secret:
                secretName: rhsm-subscriptions
          restartPolicy: Always
          terminationGracePeriodSeconds: 75
      triggers:
        - type: ConfigChange
