apiVersion: v1
kind: Template
metadata:
  name: rhsm-subscriptions-postgresql

parameters:
  - name: NAMESPACE
    description: Name of your project (e.g. myproject)
  - name: DB_CAPACITY
    description: Amount of storage to allocate to the database (e.g. 50Gi)
    value: "50Gi"

objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: rhsm-subscriptions-data
      namespace: "${NAMESPACE}"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${DB_CAPACITY}"

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: rhsm-subscriptions
      name: rhsm-subscriptions-postgresql
      namespace: "${NAMESPACE}"
    spec:
      replicas: 1
      selector:
        name: rhsm-subscriptions-postgresql
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: rhsm-subscriptions-postgresql
            app: rhsm-subscriptions
        spec:
          containers:
            - env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: rhsm-subscriptions
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: rhsm-subscriptions
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: rhsm-subscriptions
              image: openshift/postgresql
              imagePullPolicy: IfNotPresent
              livenessProbe:
                exec:
                  command:
                    - /usr/libexec/check-container
                    - --live
                initialDelaySeconds: 120
                timeoutSeconds: 10
              name: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /usr/libexec/check-container
                initialDelaySeconds: 5
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: rhsm-subscriptions-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: rhsm-subscriptions-data
              persistentVolumeClaim:
                claimName: rhsm-subscriptions-data
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: postgresql:9.6
              namespace: openshift
          type: ImageChange
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: rhsm-subscriptions
      name: rhsm-subscriptions-postgresql
      namespace: "${NAMESPACE}"
    spec:
      ports:
        - name: postgresql
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        deploymentconfig: rhsm-subscriptions-postgresql
