apiVersion: v1
kind: Template
labels:
  app: rhsm-subscriptions
  template: rhsm-subscriptions-scheduler
metadata:
  annotations:
    description: Scheduled tasks for Subscription Watch
  name: rhsm-subscriptions-scheduler

parameters:
  - name: LOGGING_LEVEL_ROOT
    value: WARN
  - name: LOGGING_LEVEL
    value: INFO
  - name: KAFKA_BOOTSTRAP_HOST
    required: true
  - name: PURGE_SNAPSHOT_SCHEDULE
    value: 0 3 * * *
  - name: CAPTURE_SNAPSHOT_SCHEDULE
    value: 0 1 * * *
  - name: CAPTURE_HOURLY_SNAPSHOT_SCHEDULE
    value: 0 0 * * *
  - name: OPENSHIFT_METERING_SCHEDULE
    value: 0 * * * *
  - name: EVENT_RECORD_RETENTION
    value: 90d
  - name: OPENSHIFT_METERING_RANGE
    value: '60'
  - name: IMAGE
    value: quay.io/cloudservices/rhsm-subscriptions
  - name: IMAGE_TAG
    value: latest
  - name: IMAGE_PULL_SECRET
    value: quay-cloudservices-pull
  - name: MEMORY_REQUEST
    value: 1000Mi
  - name: MEMORY_LIMIT
    value: 1744Mi
  - name: CPU_REQUEST
    value: 500m
  - name: CPU_LIMIT
    value: 1900m
  - name: HOURLY_TALLY_OFFSET
    value: 60m
  - name: TOKEN_REFRESHER_IMAGE
    value: quay.io/observatorium/token-refresher:master-2021-02-05-5da9663
  - name: TOKEN_REFRESHER_CPU_REQUEST
    value: 50m
  - name: TOKEN_REFRESHER_CPU_LIMIT
    value: 100m
  - name: TOKEN_REFRESHER_MEMORY_REQUEST
    value: 128Mi
  - name: TOKEN_REFRESHER_MEMORY_LIMIT
    value: 150Mi
  # TODO: this should be removed once OCM has non-standard billing_model clusters
  - name: OPENSHIFT_ENABLED_ACCOUNT_PROMQL
    value: "group(min_over_time(subscription_labels{ebs_account != '', billing_model='standard'}[1h])) by (ebs_account)"

objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: openshift-metrics-cron
    spec:
      schedule: ${OPENSHIFT_METERING_SCHEDULE}
      jobTemplate:
        spec:
          activeDeadlineSeconds: 1800
          template:
            spec:
              activeDeadlineSeconds: 1800
              restartPolicy: Never
              imagePullSecrets:
                - name: ${IMAGE_PULL_SECRET}
                - name: quay-cloudservices-pull
              containers:
                - image: ${IMAGE}:${IMAGE_TAG}
                  name: rhsm-subscriptions-openshift-metering
                  env:
                    - name: SPRING_PROFILES_ACTIVE
                      value: openshift-metering-job,kafka-queue
                    - name: JAVA_MAX_MEM_RATIO
                      value: '85'
                    - name: GC_MAX_METASPACE_SIZE
                      value: '256'
                    - name: LOGGING_LEVEL_ROOT
                      value: ${LOGGING_LEVEL_ROOT}
                    - name: LOGGING_LEVEL_ORG_CANDLEPIN
                      value: ${LOGGING_LEVEL}
                    - name: KAFKA_BOOTSTRAP_HOST
                      value: ${KAFKA_BOOTSTRAP_HOST}
                    - name: OPENSHIFT_METERING_RANGE
                      value: ${OPENSHIFT_METERING_RANGE}
                    - name: HOURLY_TALLY_OFFSET
                      value: ${HOURLY_TALLY_OFFSET}
                    - name: DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.host
                    - name: DATABASE_PORT
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.port
                    - name: DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.user
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.password
                    - name: DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.name
                    - name: INVENTORY_DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.host
                    - name: INVENTORY_DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.name
                    - name: INVENTORY_DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.user
                    - name: INVENTORY_DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.password
                    - name: PROM_URL
                      value: http://localhost:8082
                    # TODO remove once non-standard billing_model lands in OCM
                    - name: OPENSHIFT_ENABLED_ACCOUNT_PROMQL
                      value: ${OPENSHIFT_ENABLED_ACCOUNT_PROMQL}
                  resources:
                    requests:
                      cpu: ${CPU_REQUEST}
                      memory: ${MEMORY_REQUEST}
                    limits:
                      cpu: ${CPU_LIMIT}
                      memory: ${MEMORY_LIMIT}

                - name: token-refresher
                  image: ${TOKEN_REFRESHER_IMAGE}
                  args:
                    - '--oidc.audience=observatorium-telemeter'
                    - '--oidc.client-id=$(CLIENT_ID)'
                    - '--oidc.client-secret=$(CLIENT_SECRET)'
                    - '--oidc.issuer-url=$(ISSUER_URL)'
                    - '--url=$(URL)'
                    - '--web.listen=:8082'
                  env:
                    - name: CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                          name: token-refresher
                          key: CLIENT_ID
                    - name: CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: token-refresher
                          key: CLIENT_SECRET
                    - name: ISSUER_URL
                      valueFrom:
                        secretKeyRef:
                          name: token-refresher
                          key: ISSUER_URL
                    - name: URL
                      valueFrom:
                        secretKeyRef:
                          name: token-refresher
                          key: URL
                  resources:
                    requests:
                      cpu: ${TOKEN_REFRESHER_CPU_REQUEST}
                      memory: ${TOKEN_REFRESHER_MEMORY_REQUEST}
                    limits:
                      cpu: ${TOKEN_REFRESHER_CPU_LIMIT}
                      memory: ${TOKEN_REFRESHER_MEMORY_LIMIT}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: rhsm-subscriptions-cron-tally
    spec:
      schedule: ${CAPTURE_SNAPSHOT_SCHEDULE}
      jobTemplate:
        spec:
          activeDeadlineSeconds: 1800
          template:
            spec:
              activeDeadlineSeconds: 1800
              restartPolicy: Never
              imagePullSecrets:
                - name: ${IMAGE_PULL_SECRET}
                - name: quay-cloudservices-pull
              containers:
                - image: ${IMAGE}:${IMAGE_TAG}
                  name: rhsm-subscriptions-cron-tally
                  env:
                    - name: SPRING_PROFILES_ACTIVE
                      value: capture-snapshots,kafka-queue
                    - name: JAVA_MAX_MEM_RATIO
                      value: '85'
                    - name: GC_MAX_METASPACE_SIZE
                      value: '256'
                    - name: LOGGING_LEVEL_ROOT
                      value: ${LOGGING_LEVEL_ROOT}
                    - name: LOGGING_LEVEL_ORG_CANDLEPIN
                      value: ${LOGGING_LEVEL}
                    - name: KAFKA_BOOTSTRAP_HOST
                      value: ${KAFKA_BOOTSTRAP_HOST}
                    - name: DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.host
                    - name: DATABASE_PORT
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.port
                    - name: DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.user
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.password
                    - name: DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.name
                    - name: INVENTORY_DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.host
                    - name: INVENTORY_DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.name
                    - name: INVENTORY_DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.user
                    - name: INVENTORY_DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.password
                  resources:
                    requests:
                      cpu: ${CPU_REQUEST}
                      memory: ${MEMORY_REQUEST}
                    limits:
                      cpu: ${CPU_LIMIT}
                      memory: ${MEMORY_LIMIT}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: rhsm-subscriptions-cron-hourly-tally
    spec:
      schedule: ${CAPTURE_HOURLY_SNAPSHOT_SCHEDULE}
      jobTemplate:
        spec:
          activeDeadlineSeconds: 1800
          template:
            spec:
              activeDeadlineSeconds: 1800
              restartPolicy: Never
              imagePullSecrets:
                - name: ${IMAGE_PULL_SECRET}
                - name: quay-cloudservices-pull
              containers:
                - image: ${IMAGE}:${IMAGE_TAG}
                  name: rhsm-subscriptions-cron-hourly-tally
                  env:
                    - name: SPRING_PROFILES_ACTIVE
                      value: capture-hourly-snapshots,kafka-queue
                    - name: JAVA_MAX_MEM_RATIO
                      value: '85'
                    - name: GC_MAX_METASPACE_SIZE
                      value: '256'
                    - name: LOGGING_LEVEL_ROOT
                      value: ${LOGGING_LEVEL_ROOT}
                    - name: LOGGING_LEVEL_ORG_CANDLEPIN
                      value: ${LOGGING_LEVEL}
                    - name: KAFKA_BOOTSTRAP_HOST
                      value: ${KAFKA_BOOTSTRAP_HOST}
                    - name: DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.host
                    - name: DATABASE_PORT
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.port
                    - name: DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.user
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.password
                    - name: DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.name
                    - name: INVENTORY_DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.host
                    - name: INVENTORY_DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.name
                    - name: INVENTORY_DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.user
                    - name: INVENTORY_DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.password
                  resources:
                    requests:
                      cpu: ${CPU_REQUEST}
                      memory: ${MEMORY_REQUEST}
                    limits:
                      cpu: ${CPU_LIMIT}
                      memory: ${MEMORY_LIMIT}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: rhsm-subscriptions-cron-purge
    spec:
      schedule: ${PURGE_SNAPSHOT_SCHEDULE}
      jobTemplate:
        spec:
          activeDeadlineSeconds: 1800
          template:
            spec:
              activeDeadlineSeconds: 1800
              restartPolicy: Never
              imagePullSecrets:
                - name: ${IMAGE_PULL_SECRET}
                - name: quay-cloudservices-pull
              containers:
                - image: ${IMAGE}:${IMAGE_TAG}
                  name: rhsm-subscriptions-cron-purge
                  env:
                    - name: SPRING_PROFILES_ACTIVE
                      value: purge-snapshots,kafka-queue
                    - name: JAVA_MAX_MEM_RATIO
                      value: '85'
                    - name: GC_MAX_METASPACE_SIZE
                      value: '256'
                    - name: LOGGING_LEVEL_ROOT
                      value: ${LOGGING_LEVEL_ROOT}
                    - name: LOGGING_LEVEL_ORG_CANDLEPIN
                      value: ${LOGGING_LEVEL}
                    - name: KAFKA_BOOTSTRAP_HOST
                      value: ${KAFKA_BOOTSTRAP_HOST}
                    - name: EVENT_RECORD_RETENTION
                      value: ${EVENT_RECORD_RETENTION}
                    - name: DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.host
                    - name: DATABASE_PORT
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.port
                    - name: DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.user
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.password
                    - name: DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: rhsm-db
                          key: db.name
                    - name: INVENTORY_DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.host
                    - name: INVENTORY_DATABASE_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.name
                    - name: INVENTORY_DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.user
                    - name: INVENTORY_DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: host-inventory-db-readonly
                          key: db.password
                  resources:
                    requests:
                      cpu: ${CPU_REQUEST}
                      memory: ${MEMORY_REQUEST}
                    limits:
                      cpu: ${CPU_LIMIT}
                      memory: ${MEMORY_LIMIT}
