apiVersion: v1
kind: Template
metadata:
  name: rhsm-subscriptions

parameters:
  - name: LOGGING_LEVEL_ROOT
    value: WARN
  - name: LOGGING_LEVEL
    value: INFO
  - name: RBAC_HOST
    required: true
  - name: KAFKA_BOOTSTRAP_HOST
    required: true
  - name: KAFKA_SCHEMA_REGISTRY_HOST
    required: true
  - name: KAFKA_MESSAGE_THREADS
    value: '24'
  - name: KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS
    value: '3600000'
  - name: REPLICAS
    value: '1'
  - name: IMAGE_TAG
    value: latest
  - name: MEMORY_REQUEST
    value: 100Mi
  - name: MEMORY_LIMIT
    value: 2Gi
  - name: CPU_REQUEST
    value: 200m
  - name: CPU_LIMIT
    value: '1'

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rhsm-subscriptions-config
      labels:
        app: rhsm-subscriptions
    data:
      logback.xml: |-
        <?xml version="1.0" encoding="UTF-8"?>
        <configuration scan="true" scanPeriod="60 seconds">
          <contextName>rhsm-subscriptions</contextName>
          <appender name="ConsoleAppender" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
          </appender>

          <logger name="org.candlepin" level="{{ log_level }}"/>

          <root level="WARN">
            <appender-ref ref="ConsoleAppender" />
          </root>
        </configuration>

      subscriptions.properties: |-
        rhsm-subscriptions.dev-mode=${DEV_MODE:false}
        rhsm-subscriptions.prettyPrintJson=${PRETTY_PRINT_JSON:false}
        rhsm-subscriptions.package_uri_mappings.org.candlepin.subscriptions=${PATH_PREFIX:api}/${APP_NAME:rhsm-subscriptions}/v1

        rhsm-subscriptions.inventory-service.datasource.url=jdbc:postgresql://${INVENTORY_DATABASE_HOST:localhost}/${INVENTORY_DATABASE_DATABASE:inventory}
        rhsm-subscriptions.inventory-service.datasource.username=${INVENTORY_DATABASE_USERNAME:insights}
        rhsm-subscriptions.inventory-service.datasource.password=${INVENTORY_DATABASE_PASSWORD:insights}
        rhsm-subscriptions.inventory-service.datasource.driver-class-name=org.postgresql.Driver
        rhsm-subscriptions.inventory-service.datasource.platform=postgresql

        # Use Spring Resource notation for this (e.g. "classpath:" or "file:")
        rhsm-subscriptions.product_id_to_products_map_resource_location=classpath:product_id_to_products_map.yaml
        rhsm-subscriptions.role_to_products_map_resource_location=classpath:role_to_products_map.yaml
        rhsm-subscriptions.product_whitelist_resource_location=${PRODUCT_WHITELIST_RESOURCE_LOCATION:}
        rhsm-subscriptions.account_list_resource_location=${ACCOUNT_LIST_RESOURCE_LOCATION:}

        rhsm-subscriptions.datasource.url=jdbc:postgresql://${RHSM_SUBSCRIPTIONS_DATABASE_HOSTNAME:localhost}:${RHSM_SUBSCRIPTIONS_DATABASE_PORT:5432}/${RHSM_SUBSCRIPTIONS_DATABASE_NAME:rhsm-subscriptions}
        rhsm-subscriptions.datasource.username=${RHSM_SUBSCRIPTIONS_DATABASE_USER:rhsm-subscriptions}
        rhsm-subscriptions.datasource.password=${RHSM_SUBSCRIPTIONS_DATABASE_PASSWORD:rhsm-subscriptions}
        rhsm-subscriptions.datasource.driver-class-name=org.postgresql.Driver
        rhsm-subscriptions.datasource.platform=postgresql

        # Capture snapshot schedule
        rhsm-subscriptions.jobs.captureSnapshotSchedule=${CAPTURE_SNAPSHOT_SCHEDULE:0 0/5 * * * ?}
        rhsm-subscriptions.account-batch-size=${ACCOUNT_BATCH_SIZE:1}

        # Tally retention policy
        rhsm-subscriptions.tally-retention-policy.daily=${TALLY_RETENTION_DAILY:37}
        rhsm-subscriptions.tally-retention-policy.weekly=${TALLY_RETENTION_WEEKLY:12}
        rhsm-subscriptions.tally-retention-policy.monthly=${TALLY_RETENTION_MONTHLY:12}
        rhsm-subscriptions.tally-retention-policy.quarterly=${TALLY_RETENTION_QUARTERLY:16}
        rhsm-subscriptions.tally-retention-policy.yearly=${TALLY_RETENTION_YEARLY:5}

        # Default Quartz datasource.  Override by pulling in another rhsm-subscriptions.properties file via an
        # -Dspring.config.additional-location argument
        rhsm-subscriptions.quartz.datasource.platform=hsqldb

        ##########################
        # kafka configuration
        ##########################

        # Use profile "kafka-queue" to enable Kafka integration
        # Use profile "worker" to enable Kafka listeners
        rhsm-subscriptions.tasks.task-group=${KAFKA_TASK_GROUP:platform.rhsm-subscriptions.tasks}

        # if no offset commit exists yet, set to earliest
        spring.kafka.consumer.properties.auto.offset.reset=earliest

        # Required kafka defaults
        spring.kafka.consumer.properties.max.poll.records=1
        spring.kafka.consumer.properties.max.poll.interval.ms=${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:1800000}

        # The number of threads that will be processing messages (should match
        # the number of partitions on the queue)
        spring.kafka.listener.concurrency=${KAFKA_MESSAGE_THREADS:1}
        spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_HOST:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
        spring.kafka.consumer.properties.reconnect.backoff.ms=${KAFKA_CONSUMER_RECONNECT_BACKOFF_MS:2000}
        spring.kafka.consumer.properties.reconnect.backoff.max.ms=${KAFKA_CONSUMER_RECONNECT_BACKOFF_MAX_MS:10000}
        spring.kafka.consumer.properties.default.api.timeout.ms=${KAFKA_API_RECONNECT_TIMEOUT_MS:480000}

        ###################################
        # Schema Registry configuration
        ###################################

        spring.kafka.properties.schema.registry.url=${KAFKA_SCHEMA_REGISTRY_SCHEME:http}://${KAFKA_SCHEMA_REGISTRY_HOST:localhost}:${KAFKA_SCHEMA_REGISTRY_PORT:8081}
        spring.kafka.properties.auto.register.schemas=${KAFKA_AUTO_REGISTER_SCHEMAS:false}

        ###################################
        # RBAC Configuration
        ###################################
        rhsm-subscriptions.rbacApplicationName=${RBAC_APPLICATION_NAME:subscriptions}
        rhsm-subscriptions.rbac-service.useStub=${RBAC_USE_STUB:false}
        rhsm-subscriptions.rbac-service.url=http://${RBAC_HOST:localhost}:${RBAC_PORT:8819}/api/rbac/v1
        rhsm-subscriptions.rbac-service.maxConnections=${RBAC_MAX_CONNECTIONS:100}

      ssl.properties: |-
        # force client cert auth for ingress endpoints
        server.port=8443
        server.ssl.client-auth=NEED
        server.ssl.enabled=true

        server.ssl.key-store=${KEYSTORE}
        server.ssl.key-store-password=${KEYSTORE_PASSWORD}

        server.ssl.trust-store=${TRUSTSTORE}
        server.ssl.trust-store-password=${TRUSTSTORE_PASSWORD}

        # put /actuator calls on 8080
        management.server.port=8080
        management.server.ssl.enabled=false

      rhel-product-list.txt: |-
        {% for product in rhel_product_list %}{{ product }}
        {% endfor %}

      product-whitelist.txt: |-
        {% for product in whitelisted_products %}{{ product }}
        {% endfor %}

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: rhsm-subscriptions
      name: rhsm-subscriptions
    spec:
      replicas: ${REPLICAS}
      selector:
        deploymentconfig: rhsm-subscriptions
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: rhsm-subscriptions
            deploymentconfig: rhsm-subscriptions
          annotations:
            prometheus.io/path: /actuator/prometheus
            prometheus.io/port: '8080'
            prometheus.io/scrape: 'true'
        spec:
          containers:
            - image: quay.io/cloudservices/rhsm-subscriptions:${IMAGE_TAG}
              name: rhsm-subscriptions
              env:
                - name: JAVA_OPTIONS
                  value: -Dlogging.config=/config/logback.xml -Dspring.config.additional-location=file:/config/subscriptions.properties -Dspring.profiles.active=api
                - name: JAVA_MAX_MEM_RATIO
                  value: '85'
                - name: GC_MAX_METASPACE_SIZE
                  value: '256'
                - name: LOGGING_LEVEL_ROOT
                  value: ${LOGGING_LEVEL_ROOT}
                - name: LOGGING_LEVEL_ORG_CANDLEPIN
                  value: ${LOGGING_LEVEL}
                - name: KAFKA_BOOTSTRAP_HOST
                  value: ${KAFKA_BOOTSTRAP_HOST}
                - name: KAFKA_SCHEMA_REGISTRY_HOST
                  value: ${KAFKA_SCHEMA_REGISTRY_HOST}
                - name: KAFKA_MESSAGE_THREADS
                  value: ${KAFKA_MESSAGE_THREADS}
                - name: KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS
                  value: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS}
                - name: RBAC_HOST
                  value: ${RBAC_HOST}
                - name: RBAC_PORT
                  value: ${RBAC_PORT}
                - name: RHSM_SUBSCRIPTIONS_DATABASE_HOSTNAME
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-host
                - name: RHSM_SUBSCRIPTIONS_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-name
                - name: RHSM_SUBSCRIPTIONS_DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-user
                - name: RHSM_SUBSCRIPTIONS_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions
                      key: database-password
                - name: INVENTORY_DATABASE_HOSTNAME
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: hostname
                - name: INVENTORY_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: database-name
                - name: INVENTORY_DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: username
                - name: INVENTORY_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: inventory-rds-db
                      key: password
                - name: KEYSTORE
                  value: /ssl/keystore.jks
                - name: KEYSTORE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions-ssl
                      key: keystore-password
                - name: TRUSTSTORE
                  value: /ssl/truststore.jks
                - name: TRUSTSTORE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rhsm-subscriptions-ssl
                      key: truststore-password
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 3
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 3
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8778
                  name: jolokia
                  protocol: TCP
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: ssl
                  mountPath: /ssl
              workingDir: /
          volumes:
            - name: config
              configMap:
                name: rhsm-subscriptions-config
            - name: ssl
                secret:
                  secretName: rhsm-subscriptions-ssl
          restartPolicy: Always
          terminationGracePeriodSeconds: 75
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: rhsm-subscriptions
      name: rhsm-subscriptions
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: rhsm-subscriptions
