---
apiVersion: v1
kind: Template
metadata:
  name: rhsm-subscriptions-egress

parameters:
  - name: NAMESPACE
    description: Name of your project (e.g. myproject)
  - name: IMAGE_NAMESPACE
    description: The namespace containing the build image.
    value: buildfactory
  - name: IMAGE_TAG
    description: The image tag that should be used for the deployment
    value: latest
  - name: S3_BUCKET
    description: "S3 bucket to drop the data export file"
    required: true
  - name: EXPORTED_TABLES
    description: "Space separated list of DB tables that should be exported when the cron job is run"
    value: "tally_snapshots subscription_capacity"
    required: true

objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    labels:
      app: rhsm-subscriptions
    name: rhsm-subscriptions-egress
    namespace: "${NAMESPACE}"
  spec:
    schedule: "@daily"
    jobTemplate:
      spec:
        activeDeadlineSeconds: 1800
        template:
          metadata:
            labels:
              parent: rhsm-subscriptions-egress
          spec:
            restartPolicy: Never
            containers:
              - image: rhsm-subscriptions-egress
                imagePullPolicy: Always
                name: rhsm-subscriptions-egress
                command: ["/bin/sh", "-c"]
                args:
                  - >-
                    set -ex;
                    for table in $EXPORTED_TABLES; do
                      echo "Table '${table}': Data collection started.";
                      psql -h $POSTGRESQL_SERVICE_HOST -U $POSTGRESQL_USER $POSTGRESQL_DATABASE -c "COPY $table TO STDOUT CSV" |
                      gzip -9 |
                      aws s3 cp - s3://${S3_BUCKET}/$(date -I)/${table}.csv.gz;
                      echo "Table '${table}': Dump uploaded to intermediate storage.";
                    done;
                    echo "Success.";
                resources:
                  limits:
                    cpu: 500m
                    memory: 256Mi
                  requests:
                    cpu: 250m
                    memory: 256Mi
                env:
                  - name: POSTGRESQL_SERVICE_HOST
                    valueFrom:
                      secretKeyRef:
                        name: rhsm-subscriptions
                        key: database-host
                        optional: false
                  - name: POSTGRESQL_USER
                    valueFrom:
                      secretKeyRef:
                        name: rhsm-subscriptions
                        key: database-user
                        optional: false
                  - name: POSTGRESQL_DATABASE
                    valueFrom:
                      secretKeyRef:
                        name: rhsm-subscriptions
                        key: database-name
                        optional: false
                  - name: PGPASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: rhsm-subscriptions
                        key: database-password
                        optional: false
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: rhsm-subscriptions
                        key: subscriptions_egress_s3_access_key
                        optional: false
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: rhsm-subscriptions
                        key: subscription_egress_s3_secret_key
                        optional: false
                  - name: S3_BUCKET
                    value: ${S3_BUCKET}
                  - name: EXPORTED_TABLES
                    value: ${EXPORTED_TABLES}
