apiVersion: v1
kind: Template
metadata:
  name: rhsm-conduit-syncjob
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${APPLICATION_NAME}-syncjob
    labels:
      app: ${APPLICATION_NAME}
  spec:
    schedule: ${SYNC_SCHEDULE}
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: ${APPLICATION_NAME}-syncjob
          spec:
            containers:
            - name: ${APPLICATION_NAME}-syncjob
              image: registry.access.redhat.com/rhel7
              args: ['/bin/bash', '-c', 'echo ${SYNC_ORGS} | tr " " "\n" | xargs -l -I{} curl -v -X POST ${SYNC_ENDPOINT}/{}']
            restartPolicy: OnFailure
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  value: rhsm-conduit
  required: false
- description: Sync schedule
  displayName: Sync schedule
  name: SYNC_SCHEDULE
  value: '0 3 * * *'
  required: false
- description: List of orgs to sync on a regular basis, separated by a space or newline
  displayName: Sync orgs
  name: SYNC_ORGS
  required: true
- description: Sync endpoint (ex. http://rhsm-conduit.example.com:8080/rhsm-conduit/inventory)
  displayName: Sync endpoint
  name: SYNC_ENDPOINT
  required: true
