apiVersion: v1
kind: Template
metadata:
  name: rhsm-conduit-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  value: rhsm-conduit
  required: false
- description: 'Custom hostname for http service route.  Leave blank for default hostname, e.g.: <application-name>-<project>.<default-domain-suffix>'
  displayName: Custom http Route Hostname
  name: HOSTNAME_HTTP
  value: ''
  required: false
